[workspace]
members = ["crabdis", "crabdis-core", "crabdis-macros"]
resolver = "2"

[workspace.package]
version = "0.1.40"
edition = "2024"
license = "MIT"
repository = "https://github.com/pxseu/crabdis"
homepage = "https://github.com/pxseu/crabdis#readme"

[workspace.dependencies]
crabdis-core = { path = "crabdis-core", version = "0.1.40" }
crabdis-macros = { path = "crabdis-macros", version = "0.1.40" }

[workspace.dependencies.tokio]
version = "1.48"

[profile.release]
strip = true
lto = "fat"
opt-level = 3
panic = "abort"

[profile.test]
inherits = "release"

[profile.bench]
inherits = "release"

[profile.dev]
strip = false
debug = true
opt-level = 3
panic = "unwind"
