[workspace]
members = ["crabdis", "crabdis-core"]
resolver = "2"

[workspace.package]
version = "0.1.31"
edition = "2024"
license = "MIT"
repository = "https://github.com/pxseu/crabdis"
homepage = "https://github.com/pxseu/crabdis#readme"

[workspace.dependencies]
crabdis-core = { path = "crabdis-core", version = "0.1.30" }

[profile.release]
strip = true
lto = true
opt-level = 3
panic = "abort"

[profile.test]
inherits = "release"

[profile.bench]
inherits = "release"

[profile.dev]
debug = true
opt-level = 3
panic = "unwind"
