[package]
name = "crabdis"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.36", features = ["full"] }
clap = { version = "4.5.2", features = [] }
tokio-util = { version = "0.7.10", features = ["io"] }
