[package]
name = "crabdis-core"
description = "Core types and RESP protocol implementation for crabdis"
readme = "../README.md"
keywords = ["redis", "resp", "protocol", "serialization"]
categories = ["encoding", "network-programming"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
tokio = { workspace = true, features = ["io-util", "time", "sync"] }

[dev-dependencies]
criterion = { version = "0.8", features = ["async_tokio"] }
tokio = { workspace = true, features = ["full", "tracing"] }


[[bench]]
name = "int_parser"
harness = false

[[bench]]
name = "value_benchmarks"
harness = false
