[package]
name = "crabdis-macros"
description = "Macros for Crabdis"
readme = "../README.md"
keywords = ["redis", "resp", "protocol", "serialization"]
categories = ["macros", "network-programming"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
proc-macro = true

[dependencies]
darling = "0.23.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
