[package]
name = "crabdis"
description = "It's like Redis but a bit rusty..."
readme = "../README.md"
keywords = ["redis", "key-value", "database", "resp", "server"]
categories = ["database", "network-programming", "web-programming"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
crabdis-core.workspace = true
log = "0.4"
fern = "0.7"
clap = { version = "4.5", features = ["derive"] }
tokio = { workspace = true, features = [
    "net",
    "time",
    "io-util",
    "rt-multi-thread",
    "sync",
    "macros",
] }
async-trait = "0.1"
glob = "0.3"
