define_commands! {
    auth => Auth,
    client => Client,
    command => Command,
    config => Config,
    dbsize => DBSize,
    decr => Decr,
    del => Del,
    exists => Exists,
    flushdb => FlushDB,
    get => Get,
    hello => Hello,
    incr => Incr,
    info => Info,
    keys => Keys,
    mget => MGet,
    mset => MSet,
    ping => Ping,
    quit => Quit,
    renamenx => RenameNx,
    scan => Scan,
    select => Select,
    set => Set,
    r#type => Type,
}
