name: Test

on:
  push:
    branches:
      - "**"

jobs:
  fmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --all -- --check

  test:
    name: Test on ${{ matrix.os }} (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            flags: --all-features

          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            flags: --all-features

          - target: x86_64-apple-darwin
            os: macOS-latest
            flags: --all-features

          - target: aarch64-apple-darwin
            os: macOS-latest
            flags: --all-features

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            flags: --all-features

          - target: aarch64-pc-windows-msvc
            os: windows-latest
            flags: --all-features

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
          components: rustfmt, clippy

      - name: Install Cross [Linux]
        if: matrix.os == 'ubuntu-latest'
        run: cargo install cross

      - name: Run Clippy
        run: ${{ matrix.os == 'ubuntu-latest' && 'cross' || 'cargo' }} clippy --all-targets --locked ${{ matrix.flags }} --target ${{ matrix.target }} -- -D warnings

      - name: Run tests
        run: ${{ matrix.os == 'ubuntu-latest' && 'cross' || 'cargo' }} test --locked ${{ matrix.flags }} --target ${{ matrix.target }}
